# Generated by Django 4.1.1 on 2022-09-07 23:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stock_models',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4)),
                ('ticket', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('acao', 'Ação'), ('fii', 'Fundo de Investimento Imobiliário'), ('bdr', 'Brazilian Depositary Receipts')], max_length=5)),
                ('cnpj', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
    ]
